"""Initial migration

Revision ID: e10cfc054bf2
Revises: 
Create Date: 2020-04-23 23:01:30.982787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e10cfc054bf2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mahasiswa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('NIM', sa.CHAR(length=10), nullable=False),
    sa.Column('Nama', sa.CHAR(length=100), nullable=False),
    sa.Column('Alamat', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('NIM'),
    sa.UniqueConstraint('Nama')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mahasiswa')
    # ### end Alembic commands ###
